/*
 * generated by Xtext
 */
package edu.upb.lp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RebotinolRuntimeModule extends edu.upb.lp.AbstractRebotinolRuntimeModule {

}
