/*
* generated by Xtext
*/
package edu.upb.lp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RebotinolStandaloneSetup extends RebotinolStandaloneSetupGenerated{

	public static void doSetup() {
		new RebotinolStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

