/*
* generated by Xtext
*/
package edu.upb.lp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.upb.lp.services.ReboConfGrammarAccess;

public class ReboConfParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ReboConfGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.upb.lp.parser.antlr.internal.InternalReboConfParser createParser(XtextTokenStream stream) {
		return new edu.upb.lp.parser.antlr.internal.InternalReboConfParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Configuration";
	}
	
	public ReboConfGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ReboConfGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
