/*
 * generated by Xtext
 */
package edu.upb.lp.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RebotinolUiModule extends edu.upb.lp.ui.AbstractRebotinolUiModule {
	public RebotinolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
