/*
* generated by Xtext
*/
package edu.upb.lp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ReboConfStandaloneSetup extends ReboConfStandaloneSetupGenerated{

	public static void doSetup() {
		new ReboConfStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

