/*
* generated by Xtext
*/
package edu.upb.lp.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import edu.upb.lp.services.RebotinolGrammarAccess;

public class RebotinolParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RebotinolGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected edu.upb.lp.parser.antlr.internal.InternalRebotinolParser createParser(XtextTokenStream stream) {
		return new edu.upb.lp.parser.antlr.internal.InternalRebotinolParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "RebotinolProgram";
	}
	
	public RebotinolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RebotinolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
