/*
 * generated by Xtext
 */
package edu.upb.lp.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.upb.lp.ui.internal.ReboConfActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReboConfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ReboConfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ReboConfActivator.getInstance().getInjector(ReboConfActivator.EDU_UPB_LP_REBOCONF);
	}
	
}
