/**
 * generated by Xtext
 */
package edu.upb.lp.ui.contentassist;

import edu.upb.lp.ui.contentassist.AbstractRebotinolProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class RebotinolProposalProvider extends AbstractRebotinolProposalProvider {
}
