/*
 * generated by Xtext
 */
package edu.upb.lp.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.upb.lp.ui.internal.RebotinolActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RebotinolExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RebotinolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RebotinolActivator.getInstance().getInjector(RebotinolActivator.EDU_UPB_LP_REBOTINOL);
	}
	
}
