/*
 * generated by Xtext
 */
package edu.upb.lp.validation

//import org.eclipse.xtext.validation.Check

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class RebotinolValidator extends AbstractRebotinolValidator {

}
