/*
 * generated by Xtext
 */
package edu.upb.lp.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRebotinolValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(edu.upb.lp.rebotinol.RebotinolPackage.eINSTANCE);
		return result;
	}
}
