/**
 * generated by Xtext
 */
package edu.upb.lp.validation;

import com.google.common.base.Objects;
import edu.upb.lp.reboConf.Fraction;
import edu.upb.lp.reboConf.Line;
import edu.upb.lp.reboConf.Matrix;
import edu.upb.lp.reboConf.ReboConfPackage;
import edu.upb.lp.validation.AbstractReboConfValidator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.validation.Check;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 * 
 * @author Alexis Marechal
 */
@SuppressWarnings("all")
public class ReboConfValidator extends AbstractReboConfValidator {
  @Check
  public void checkMatrixSize(final Line line) {
    final int lineSize = line.getEls().size();
    final int firstSize = this.getMatrixLineSize(line);
    if ((lineSize != firstSize)) {
      int _size = line.getEls().size();
      String _plus = ("Todas las filas de una matriz deben tener el mismo tamaño. Esta fila tiene " + Integer.valueOf(_size));
      String _plus_1 = (_plus + 
        " elementos, mientras que la primera fila tiene ");
      String _plus_2 = (_plus_1 + Integer.valueOf(firstSize));
      String _plus_3 = (_plus_2 + " elementos");
      this.error(_plus_3, 
        ReboConfPackage.Literals.LINE__ELS);
    }
  }
  
  public int getMatrixLineSize(final Line line) {
    EObject container = ((EObject) line);
    while ((!(container instanceof Matrix))) {
      container = container.eContainer();
    }
    final Matrix mat = ((Matrix) container);
    return mat.getLines().get(0).getEls().size();
  }
  
  @Check
  public void checkFractionsDenominators(final Fraction fr) {
    edu.upb.lp.reboConf.Integer _denominator = fr.getDenominator();
    boolean _equals = Objects.equal(_denominator, Integer.valueOf(0));
    if (_equals) {
      this.error(
        "Una fracción no puede tener un denominador nulo", 
        ReboConfPackage.Literals.FRACTION__DENOMINATOR);
    }
  }
}
