/**
 * generated by Xtext
 */
package edu.upb.lp.validation;

import edu.upb.lp.validation.AbstractReboConfValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ReboConfValidator extends AbstractReboConfValidator {
}
